# Generated by Django 4.1.7 on 2023-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_collected_money_userbuybook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collected_money',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=19),
        ),
    ]
