# Generated by Django 4.1.7 on 2023-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_money_customuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
